//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebRole.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RecommendedNamesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RecommendedNamesEntities object using the connection string found in the 'RecommendedNamesEntities' section of the application configuration file.
        /// </summary>
        public RecommendedNamesEntities() : base("name=RecommendedNamesEntities", "RecommendedNamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecommendedNamesEntities object.
        /// </summary>
        public RecommendedNamesEntities(string connectionString) : base(connectionString, "RecommendedNamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecommendedNamesEntities object.
        /// </summary>
        public RecommendedNamesEntities(EntityConnection connection) : base(connection, "RecommendedNamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RelatedName> RelatedNames
        {
            get
            {
                if ((_RelatedNames == null))
                {
                    _RelatedNames = base.CreateObjectSet<RelatedName>("RelatedNames");
                }
                return _RelatedNames;
            }
        }
        private ObjectSet<RelatedName> _RelatedNames;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FirstName> FirstNames
        {
            get
            {
                if ((_FirstNames == null))
                {
                    _FirstNames = base.CreateObjectSet<FirstName>("FirstNames");
                }
                return _FirstNames;
            }
        }
        private ObjectSet<FirstName> _FirstNames;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RelatedNames EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRelatedNames(RelatedName relatedName)
        {
            base.AddObject("RelatedNames", relatedName);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FirstNames EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFirstNames(FirstName firstName)
        {
            base.AddObject("FirstNames", firstName);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="isMale">No Metadata Documentation available.</param>
        public int IncrementGender(global::System.String name, Nullable<global::System.Boolean> isMale)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter isMaleParameter;
            if (isMale.HasValue)
            {
                isMaleParameter = new ObjectParameter("IsMale", isMale);
            }
            else
            {
                isMaleParameter = new ObjectParameter("IsMale", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction("IncrementGender", nameParameter, isMaleParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="startsWith">No Metadata Documentation available.</param>
        public ObjectResult<NamesByPrefixResult> GetNamesByPrefix(global::System.String startsWith)
        {
            ObjectParameter startsWithParameter;
            if (startsWith != null)
            {
                startsWithParameter = new ObjectParameter("StartsWith", startsWith);
            }
            else
            {
                startsWithParameter = new ObjectParameter("StartsWith", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<NamesByPrefixResult>("GetNamesByPrefix", startsWithParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RecommendedNamesModel", Name="FirstName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FirstName : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FirstName object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="count">Initial value of the Count property.</param>
        /// <param name="sum">Initial value of the Sum property.</param>
        /// <param name="maleCount">Initial value of the MaleCount property.</param>
        /// <param name="femaleCount">Initial value of the FemaleCount property.</param>
        public static FirstName CreateFirstName(global::System.String name, global::System.Int32 count, global::System.Int32 sum, global::System.Int32 maleCount, global::System.Int32 femaleCount)
        {
            FirstName firstName = new FirstName();
            firstName.Name = name;
            firstName.Count = count;
            firstName.Sum = sum;
            firstName.MaleCount = maleCount;
            firstName.FemaleCount = femaleCount;
            return firstName;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private global::System.Int32 _Count;
        partial void OnCountChanging(global::System.Int32 value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                OnSumChanging(value);
                ReportPropertyChanging("Sum");
                _Sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sum");
                OnSumChanged();
            }
        }
        private global::System.Int32 _Sum;
        partial void OnSumChanging(global::System.Int32 value);
        partial void OnSumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaleCount
        {
            get
            {
                return _MaleCount;
            }
            set
            {
                OnMaleCountChanging(value);
                ReportPropertyChanging("MaleCount");
                _MaleCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaleCount");
                OnMaleCountChanged();
            }
        }
        private global::System.Int32 _MaleCount;
        partial void OnMaleCountChanging(global::System.Int32 value);
        partial void OnMaleCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FemaleCount
        {
            get
            {
                return _FemaleCount;
            }
            set
            {
                OnFemaleCountChanging(value);
                ReportPropertyChanging("FemaleCount");
                _FemaleCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FemaleCount");
                OnFemaleCountChanged();
            }
        }
        private global::System.Int32 _FemaleCount;
        partial void OnFemaleCountChanging(global::System.Int32 value);
        partial void OnFemaleCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RecommendedNamesModel", Name="RelatedName")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelatedName : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RelatedName object.
        /// </summary>
        /// <param name="seed">Initial value of the Seed property.</param>
        /// <param name="result">Initial value of the Result property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="resultSum">Initial value of the ResultSum property.</param>
        /// <param name="resultCount">Initial value of the ResultCount property.</param>
        public static RelatedName CreateRelatedName(global::System.String seed, global::System.String result, global::System.Int32 weight, global::System.Int32 resultSum, global::System.Int32 resultCount)
        {
            RelatedName relatedName = new RelatedName();
            relatedName.Seed = seed;
            relatedName.Result = result;
            relatedName.Weight = weight;
            relatedName.ResultSum = resultSum;
            relatedName.ResultCount = resultCount;
            return relatedName;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Seed
        {
            get
            {
                return _Seed;
            }
            set
            {
                if (_Seed != value)
                {
                    OnSeedChanging(value);
                    ReportPropertyChanging("Seed");
                    _Seed = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Seed");
                    OnSeedChanged();
                }
            }
        }
        private global::System.String _Seed;
        partial void OnSeedChanging(global::System.String value);
        partial void OnSeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Result
        {
            get
            {
                return _Result;
            }
            set
            {
                if (_Result != value)
                {
                    OnResultChanging(value);
                    ReportPropertyChanging("Result");
                    _Result = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Result");
                    OnResultChanged();
                }
            }
        }
        private global::System.String _Result;
        partial void OnResultChanging(global::System.String value);
        partial void OnResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Int32 _Weight;
        partial void OnWeightChanging(global::System.Int32 value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultSum
        {
            get
            {
                return _ResultSum;
            }
            set
            {
                OnResultSumChanging(value);
                ReportPropertyChanging("ResultSum");
                _ResultSum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResultSum");
                OnResultSumChanged();
            }
        }
        private global::System.Int32 _ResultSum;
        partial void OnResultSumChanging(global::System.Int32 value);
        partial void OnResultSumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultCount
        {
            get
            {
                return _ResultCount;
            }
            set
            {
                OnResultCountChanging(value);
                ReportPropertyChanging("ResultCount");
                _ResultCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResultCount");
                OnResultCountChanged();
            }
        }
        private global::System.Int32 _ResultCount;
        partial void OnResultCountChanging(global::System.Int32 value);
        partial void OnResultCountChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="RecommendedNamesModel", Name="NamesByPrefixResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class NamesByPrefixResult : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NamesByPrefixResult object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sum">Initial value of the Sum property.</param>
        public static NamesByPrefixResult CreateNamesByPrefixResult(global::System.String name, global::System.Int32 sum)
        {
            NamesByPrefixResult namesByPrefixResult = new NamesByPrefixResult();
            namesByPrefixResult.Name = name;
            namesByPrefixResult.Sum = sum;
            return namesByPrefixResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                OnSumChanging(value);
                ReportPropertyChanging("Sum");
                _Sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sum");
                OnSumChanged();
            }
        }
        private global::System.Int32 _Sum;
        partial void OnSumChanging(global::System.Int32 value);
        partial void OnSumChanged();

        #endregion
    }

    #endregion
    
}
